name: "DevSecOps Pipeline for typescript based react app."

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Run the unit test cases..
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repo
        uses: actions/checkout@v4

      - name: Setup Nodejs Configuration
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependancies
        run: npm ci

      - name: Run Test Cases
        run: npm test || echo "No tests found, would add tests in a real project"

  # Check static code analysis..
  lint:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repo
        uses: actions/checkout@v4

      - name: Setup Nodejs Configuration
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependancies
        run: npm ci

      - name: Run Eslint
        run: npm run lint

  # Build the project and store to artifactory..
  build:
    name: Build Code
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Checkout Code Repo
        uses: actions/checkout@v4

      - name: Setup Nodejs Configuration
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependancies
        run: npm ci

      - name: Build the application
        run: npm run build

      - name: Project folder structure
        run: ls -ltr

      - name: Upload the build artifactory
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
